### ISSUE TITLE
[BUG] 添加应用后无法打开目标应用，卡开屏

### ISSUE THREAD

**Issue by wbappz** [BlackBoxing/BlackBox#1]
**Describe the bug** / **描述一下这个错误**
清晰而简明地描述什么是错误。

在用最新master分支源码编译的blackbox中，添加应用后无法打开目标应用(尝试过多个应用)，卡开屏，之前尝试过原版和refgd维护的blackbox,也是相同结果

**To Reproduce** / **复现步骤**

**Expected behavior** / **预期的行为**
清晰而简明地描述你所期望发生的事情。

**Screenshots** / **截图**
如果有，请添加屏幕截图以帮助解释你的问题。

**Mobile Phone Info** / **手机信息**

Xiaomi / Android12/ miui13 22.7.18

**Logcat** / **日志**
If you are a developer or capable please provide logs for us to analyze.
如果你是开发者或者有能力的请提供日志供我们分析。

blackbox未能生成日志,尝试过使用scoop捕获日志，未能获取日志

**Additional context** / **额外内容**
在此添加关于该问题的任何其他内容。

**APK**
If applicable, add the apk file for me to test.
如果有，请添加APK文件给我测试。

**Comment by BlackBoxing** [comment]
没有安卓12的手机，目前无法修复

**Comment by wbappz** [comment]
蓝瘦

**Comment by BlackBoxing** [comment]
你可以考虑支援点，我去买个安卓12
